import asyncio
from dotenv import load_dotenv
from claude_agent_sdk import (
    query, ClaudeAgentOptions,
    AssistantMessage, TextBlock, ToolUseBlock, ToolResultBlock, ResultMessage,
)

load_dotenv(dotenv_path=".env") #load environment variables from .env file

Task = "List the python files in this project and briefly describt what each does."

async def main() -> None:
    options = ClaudeAgentOptions(
        allowed_tools=["Bash", "Read", "Glob"],
        permission_mode="acceptEdits", #dont pause for confirmations
        cwd=".",
    )
    async for message in query(prompt=Task, options=options):   #query returns an async generator that yields messages as they are generated by the agent
        print("=" * 60) #separator for readability
        print("TYPE:", type(message).__name__) #print the type of messsage received
        if isinstance(message, AssistantMessage):   #if the message is an assistant message, print the text content
            for block in message.content: #assistant messages have a content attribute that is a list of blocks, each block can be a text block, tool use block, tool result block, or other types of blocks
                if isinstance(block, TextBlock): #TextBlock are my llm_call spans, they have a text attribute that contains the text generated by the llm for that block
                    print("  Textblock:", block.text[:200]) #print the first 200 characters of the text block
                elif isinstance(block, ToolUseBlock):   #ToolUseBlock represents a tool being used by the agent, it has a name and input arguments. it is tool_call spans(name="Bash", input="ls -la") in the agent response
                    print("  ToolUseBlock:", block.name, "| input", block.input) #print the tool name and arguments if the block is a tool use block
                elif isinstance(block, ToolResultBlock):
                    print("  ToolResultBlock:", str(getattr(block, "content", ""))[:200]) #print the first 200 characters of the tool result block content
                else:
                    print("  Other block type:", type(block).__name__) #print the type of block if its not one of the expected types
        elif isinstance(message, ResultMessage): #if the message is a result message, print the content
            print("  ResultMessage:", getattr(message, "result", None))
            print("  cost_usd:", getattr(message, "total_cost_usd", None))
            print("  duration_ms:", getattr(message, "duration_ms", None))
            print("  num_turns:", getattr(message, "num_turns", None))
            print("  is_error:", getattr(message, "is_error", None))
        else:
            print("   raw:", message) #if the message is an unexpected type, print the raw message

if __name__ == "__main__":
    asyncio.run(main())
